const express = require("express");
const router = express.Router();
router.use("/", require("./admin.route"));
router.use("/", require("./user.route"));
router.use("/", require("./car.route"));
router.use("/", require("./review.routes"));
router.use("/", require("./service.route"));
router.use("/", require("./road-assistance"));
router.use("/", require("./accessories"));
router.use("/", require("./spare-parts.route"));
router.use("/", require("./article.route"));
router.use("/", require("./vendor.route"));
router.use("/", require("./rating-review.route"));
router.use("/", require("./car-service-order.route"));
router.use("/", require("./notification.route"));
router.use("/", require("./subscriptionPlan"));
router.use("/", require("./info"));
router.use("/", require("./car-service-order-review"));
router.use("/", require("./faq.route"));
router.use("/", require("./banner"));
router.use("/", require("./privacy.route"));
router.use("/", require("./terms.route"));
router.use("/", require("./support"));
router.use("/", require("./discount"));
router.use("/", require("./payment"));
router.use("/", require("./feedback.route"));
router.use("/", require("./CarComparisonRoute"));
router.use("/", require("./UsedCarRoute"));
router.use("/", require("./carLoanRoute"));
router.use("/", require("./BookingVerificationRoute"));
module.exports = router;
